[package]
name    = "aldwin-config"
version.workspace = true
edition.workspace = true

[dependencies]
aldwin-core  = { path = "../core" }
serde         = { workspace = true }
serde_json    = { workspace = true }
serde_yaml_ng = "0.10"
thiserror     = { workspace = true }
tempfile      = "3"
dirs          = "5"
